"""Add unique constraint 2  on (user_id, skill_interest_id)

Revision ID: 034b6360f40e
Revises: 5c9a84458b87
Create Date: 2025-06-05 21:37:33.626248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '034b6360f40e'
down_revision = '5c9a84458b87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('skills_interests_embedding_idx', table_name='skills_interests')
    op.drop_constraint('uq_user_skill', 'user_interests', type_='unique')
    op.create_unique_constraint('uq_user_interest', 'user_interests', ['user_id', 'skill_interest_id'])
    op.create_unique_constraint('uq_user_skill', 'user_skills', ['user_id', 'skill_interest_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_skill', 'user_skills', type_='unique')
    op.drop_constraint('uq_user_interest', 'user_interests', type_='unique')
    op.create_unique_constraint('uq_user_skill', 'user_interests', ['user_id', 'skill_interest_id'])
    op.create_index('skills_interests_embedding_idx', 'skills_interests', ['embedding'], unique=False)
    # ### end Alembic commands ###
