"""Added Category Again

Revision ID: 0486408dd1de
Revises: f90c6a1893b5
Create Date: 2025-07-07 17:55:40.985593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0486408dd1de'
down_revision = 'f90c6a1893b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills_interests', sa.Column('category', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills_interests', 'category')
    # ### end Alembic commands ###
