"""Add unique constraint on (user_id, skill_interest_id)

Revision ID: 5c9a84458b87
Revises: a1b2c3d4e5f6
Create Date: 2025-06-05 20:32:13.618322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c9a84458b87'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_company', sa.Column('company_id', sa.UUID(), nullable=False))
    op.drop_constraint('user_company_user_company_fkey', 'user_company', type_='foreignkey')
    op.create_foreign_key(None, 'user_company', 'companies', ['company_id'], ['company_id'], ondelete='CASCADE')
    op.drop_column('user_company', 'user_company')
    op.create_unique_constraint('uq_user_skill', 'user_interests', ['user_id', 'skill_interest_id'])
    op.drop_constraint('user_tags_tag_id_fkey', 'user_tags', type_='foreignkey')
    op.drop_constraint('user_tags_user_id_fkey', 'user_tags', type_='foreignkey')
    op.create_foreign_key(None, 'user_tags', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key(None, 'user_tags', 'tags', ['tag_id'], ['tag_id'])
    op.drop_constraint('users_job_role_id_fkey', 'users', type_='foreignkey')
    op.drop_constraint('users_company_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'job_role_id')
    op.drop_column('users', 'job_title')
    op.drop_column('users', 'company_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('job_title', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('job_role_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_company_id_fkey', 'users', 'companies', ['company_id'], ['company_id'], ondelete='SET NULL')
    op.create_foreign_key('users_job_role_id_fkey', 'users', 'job_roles', ['job_role_id'], ['job_role_id'], ondelete='SET NULL')
    op.drop_constraint(None, 'user_tags', type_='foreignkey')
    op.drop_constraint(None, 'user_tags', type_='foreignkey')
    op.create_foreign_key('user_tags_user_id_fkey', 'user_tags', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key('user_tags_tag_id_fkey', 'user_tags', 'tags', ['tag_id'], ['tag_id'], ondelete='CASCADE')
    op.drop_constraint('uq_user_skill', 'user_interests', type_='unique')
    op.add_column('user_company', sa.Column('user_company', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_company', type_='foreignkey')
    op.create_foreign_key('user_company_user_company_fkey', 'user_company', 'companies', ['user_company'], ['company_id'], ondelete='CASCADE')
    op.drop_column('user_company', 'company_id')
    # ### end Alembic commands ###
