"""Add registration_category column in userregistration table

Revision ID: 9c4b90655a4a
Revises: 9f44d3f569b0
Create Date: 2025-07-09 18:40:15.906246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c4b90655a4a'
down_revision = '9f44d3f569b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_registrations', sa.Column('registration_category', sa.Enum('attendee', 'organizer', 'exhibitor', 'presenter', name='registration_category'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_registrations', 'registration_category')
    # ### end Alembic commands ###
