"""Added Type for Comapnies

Revision ID: 9f44d3f569b0
Revises: 0486408dd1de
Create Date: 2025-07-07 18:15:25.044337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f44d3f569b0'
down_revision = '0486408dd1de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('type', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'type')
    # ### end Alembic commands ###
