"""Removed type columns in skill_interests

Revision ID: f90c6a1893b5
Revises: 8d188c193f3e
Create Date: 2025-07-07 15:44:58.545922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f90c6a1893b5'
down_revision = '8d188c193f3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('companies_type_key'), 'companies', type_='unique')
    op.drop_column('companies', 'type')
    op.drop_column('skills_interests', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills_interests', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('companies', sa.Column('type', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('companies_type_key'), 'companies', ['type'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
